server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: @management.port@
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

clickhouse:
  db:
    url: "jdbc:clickhouse://localhost:8123/default"
    user: "user"
    password: "password"
    connection-timeout: 50000
    compress: false

testcontainers:
  clickhouse:
    tag: '19.17'